# Generated by Django 4.2 on 2024-02-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutMe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите галочку, чтобы скрыть слайдер",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Максимальная длинна поля 32 символа",
                        max_length=32,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "upper_text",
                    models.TextField(
                        help_text="Максимальная длина поля 600 символов",
                        max_length=600,
                        verbose_name="Текст верхний обзац",
                    ),
                ),
                (
                    "down_text",
                    models.TextField(
                        help_text="Максимальная длина поля 600 символов",
                        max_length=600,
                        verbose_name="Текст нижний обзац",
                    ),
                ),
                (
                    "list_first_line",
                    models.CharField(
                        help_text="Максимальная длинна поля 80 символа",
                        max_length=80,
                        verbose_name="Первая строка списка",
                    ),
                ),
                (
                    "list_second_line",
                    models.CharField(
                        help_text="Максимальная длинна поля 80 символа",
                        max_length=80,
                        verbose_name="Вторая строка списка",
                    ),
                ),
                (
                    "list_third_line",
                    models.CharField(
                        help_text="Максимальная длинна поля 80 символа",
                        max_length=80,
                        verbose_name="Третья строка списка",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Размер изображения 1920х900px",
                        upload_to="images/gallery_about/",
                        verbose_name="Изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Обо мне",
                "verbose_name_plural": "Обо мне",
            },
        ),
    ]
