# Generated by Django 4.2 on 2024-02-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите галочку, чтобы скрыть слайдер",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "title_big",
                    models.CharField(max_length=32, verbose_name="Заголовок"),
                ),
                (
                    "title_small",
                    models.CharField(
                        max_length=32, verbose_name="Заголовок 2"
                    ),
                ),
                (
                    "button_name",
                    models.CharField(
                        max_length=24, verbose_name="Кнопка в галерею"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Размер изображения 1920х900px",
                        upload_to="images/slider/",
                        verbose_name="Изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "слайдер",
                "verbose_name_plural": "Слайдеры",
            },
        ),
    ]
