# Generated by Django 4.2 on 2024-02-12 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите галочку, чтобы скрыть слайдер",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="максимальная длинна поля 24 символа",
                        max_length=24,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "foto_title",
                    models.CharField(
                        help_text="максимальная длинна поля 32 символа",
                        max_length=32,
                        verbose_name="Тип съемки",
                    ),
                ),
                (
                    "title_text",
                    models.TextField(verbose_name="Описание съемки"),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Размер изображения 915х700px",
                        upload_to="images/foto_type/",
                        verbose_name="Заглавное изображение",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Укажите адрес для страницы заметки. Используйте только латиницу, цифры, дефисы и знаки подчёркивания",
                        max_length=100,
                        unique=True,
                        verbose_name="Адрес для страницы с заметкой",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="MainBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="максимальная длинна поля 32 символа",
                        max_length=32,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "title_text",
                    models.TextField(
                        help_text="максимальная длина поля 120 символов",
                        max_length=120,
                        verbose_name="Описание под заголовком",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Размер изображения 1920х900px",
                        upload_to="images/gallery_main/",
                        verbose_name="Изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Баннер",
                "verbose_name_plural": "Баннеры",
            },
        ),
        migrations.CreateModel(
            name="DetailPageImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите галочку, чтобы скрыть слайдер",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="максимальная длинна поля 24 символа",
                        max_length=24,
                        verbose_name="Инфо",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Верхний ряд. Размер изображения 580x400px",
                        upload_to="images/gallery_detail_up/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="фото",
                        to="gallery.category",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "фото для категории",
                "verbose_name_plural": "Фото категорий",
            },
        ),
    ]
