# Generated by Django 4.2 on 2024-02-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите галочку, чтобы скрыть слайдер",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="максимальная длинна поля 32 символа",
                        max_length=32,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "title_text",
                    models.TextField(
                        help_text="максимальная длина поля 512 символов",
                        max_length=512,
                        verbose_name="Описание под заголовком",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="максимальная длинна поля 120 символов",
                        max_length=120,
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="максимальная длинна поля 120 символа",
                        max_length=120,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="максимальная длинна поля 120 символа",
                        max_length=120,
                        verbose_name="email",
                    ),
                ),
            ],
            options={
                "verbose_name": "контакты",
                "verbose_name_plural": "Контакты",
            },
        ),
    ]
